### ISSUE TITLE
A bug in custom.py

### ISSUE THREAD

**Issue by suzinia** [pyannote/pyannote-database#23]
Hi, I think there is a small bug in the database/custom.py file.

in line 126 through 135, the current code looks like the following.

```    
# load annotations
    if file_rttm is not None:

        if file_rttm.suffix == '.rttm':
            annotations = load_rttm(file_rttm)
        elif file_rttm.suffix == '.mdtm':
            annotations = load_mdtm(file_mdtm)
        else:
            msg = f'Unsupported format in {file_rttm}: please use RTTM.'
            raise ValueError(msg)
```

For the *.mdtm file case,
`annotations = load_mdtm(file_mdtm)` should be `annotations = load_mdtm(file_rttm)`

**Comment by hbredin** [comment]
Good catch. Thanks!

Release 2.3.1 will contain this fix.

**Comment by hbredin** [comment]
`pyannote.database` 2.3.1 has been released.
