### ISSUE TITLE
Bug/conflict : pyannote.database.util.load_rttm loads "NA" id as `nan`

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#27]
In pyannote, cluster ids are enumerated from AA to ZZ, however, when coming to "NA", if one loads the RTTM file, the "NA" id will be loaded as `nan`.
This probably has something to do with pandas' `load_cv` function.

**Comment by hbredin** [comment]
Good catch. Feel free to PR a fix: see related [`read_cvs`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) options  `keep_default_na` and `na_values`
