### ISSUE TITLE
A small bug in protocol

### ISSUE THREAD

**Issue by yinruiqing** [pyannote/pyannote-database#3]
In the new version of pyannote.database. 
`line 71` In `pyannote-database/pyannote/database/protocol/protocol.py`
```python
item[key] = preprocessor(item)
```
should be 
```python
item[key] = preprocessor(**item)
```

**Comment by hbredin** [comment]
Can you please provide me with a simple code sample where this creates a bug?

**Comment by yinruiqing** [comment]
```python
item={}
item['uri'] = 'fileName'
template = "/to/path/wav/{uri}.wav"
template.format(item)
```
In `python 2.7` and `python 3.5`
raise
`KeyError`

But we can set preprocessor to be a function to solve this problem

**Comment by hbredin** [comment]
OK. I see. There is a bug indeed for `string` preprocessors. I will fix it. 

In the meantime, here is what you can do:

* Create the configuration file `~/.pyannote/db.yml`:

```bash
$ cat ~/.pyannote/db.yml
Etape: /Users/yin/projects/corpora/etape/wav{uri}.wav
```

* Use the new `FileFinder` utility that will automagically use this configuration file to find the `wav` files:

```python
from pyannote.database.util import FileFinder
preprocessors = {'wav': FileFinder()}
database = get_database('Etape', preprocessors=preprocessors)
```

Have a look at my `~/.pyannote/db.yml` to learn more about the possible syntax.

**Comment by hbredin** [comment]
I just released `pyannote.database 0.11.2` that fixes this bug.
It also improves the documentation and describes this `FileFinder` thing in the `README.md` file.
