### ISSUE TITLE
SpeakerDiarizationProtocol stats

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#34]
annotation_duration should not consider parts that are not annotated right ?
https://github.com/pyannote/pyannote-database/blob/develop/pyannote/database/protocol/speaker_diarization.py#L194

**Comment by hbredin** [comment]
The current behavior assumes that there is no annotation outside of `annotated` support.

If there are, this is probably a bug in the provided `annotated` or `annotation` values, and it should be fixed upstream.

**Comment by PaulLerner** [comment]
> there is no annotation outside of `annotated` support

Yes but there might be annotation which we don't want to consider as annotation (as in, e.g. our current forced-alignment setup).
However [here](https://github.com/pyannote/pyannote-database/blob/develop/pyannote/database/protocol/speaker_diarization.py#L194) you take into account the whole annotation duration, regardless of the `annotated` uem.
You could fix it by adding `.crop(annotated)` to `annotation = item['annotation']`

**Comment by hbredin** [comment]
I understand the (your :-)) use case and would be happy to merge a pull request that:

- crop `annotation` by `annotated` 
- warn the user that the `crop` happened if (and only if) the original `annotation` was not fully included into `annotated`
- update the [documentation](https://github.com/pyannote/pyannote-database#generic-speaker-diarization-protocols) to reflect this **breaking** change
