### ISSUE TITLE
Feature: make paths in database.yml (optionally) relative

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#38]
I think it would be nice to be able to indicate relative paths in database.yml. This way, we could easily share plumcot corpus for example.
We could easily implement it by testing if the path (to e.g. RTTM file) `is_absolute()` and then concatenate it to the path of `PYANNOTE_DATABASE_CONFIG` if it's not.

**Comment by hbredin** [comment]
Would be nice indeed.

If we go that way, we should also improve `FileFinder` error messages better
(e.g. by telling the end user in which directories the missing file was looked for).

**Comment by PaulLerner** [comment]
Hi, 
Not sure what error messages are you talking about...

**Comment by hbredin** [comment]
I got carried away and thought you also wanted to allow relative paths in the `Databases` section of `PYANNOTE_DATABASE_CONFIG` file (handled by `FileFinder`).

Let's do that in another PR. It would be really useful as well, don't you think?

**Comment by PaulLerner** [comment]
Yes, although since we usually don't provide for the wavs, I thought it would be difficult to make the wav path relative to PYANNOTE_DATABASE_CONFIG

**Comment by hbredin** [comment]
We don't provide the wavs but can explain where to move the `database.yml` file we do provide. 

Anyway, this is now a different issue: #43.
