### ISSUE TITLE
expand database_yml path when provided

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-database#46]
Hi,

I think you should add `expand_user` here : https://github.com/pyannote/pyannote-database/blob/develop/pyannote/database/config.py#L61

Else you cannot, e.g., provide path to the database as tilde path in preprocessors in pyannote pipeline

**Comment by hbredin** [comment]
I am OK to add a call to `expanduser` here (PR?) but can you please clarify what is the problem with `pyannote.pipeline` preprocessors?

**Comment by PaulLerner** [comment]
Ok, I'll open a PR.
The problem with pyannote.pipeline is that, without expanding to user, you cannot pass a `~/tilde/path` as in the documentation : https://github.com/pyannote/pyannote-pipeline/blob/develop/pyannote/pipeline/experiment.py#L81

**Comment by hbredin** [comment]
Does it raise an error when you do?

**Comment by PaulLerner** [comment]
Not directly but then, in the pipeline, it raises a keyerror because `file['audio']`does not exists (sorry I didn't keep the log)

**Comment by hbredin** [comment]
OK. I managed to reproduce the error. Thanks. Will merge the PR.

**Comment by hbredin** [comment]
Merged in develop branch.

Let me know if you need a new release quickly.

**Comment by PaulLerner** [comment]
No it's okay, thanks :)
