### ISSUE TITLE
No loader for file with '.rttm' suffix

### ISSUE THREAD

**Issue by micahjon** [pyannote/pyannote-database#66]
Hi, I've been following the pyannote-audio data preparation tutorial, and am trying to understand how the `database.yml` files work by running code samples from the README.

For instance, using the sample [database.yml](https://github.com/pyannote/pyannote-audio/blob/master/tutorials/data_preparation/database.yml) file, the following code sample should print out some filenames:

```python
from pyannote.database import get_protocol
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset')
for resource in protocol.train():
    print(resource["uri"])
```

Instead, I get an error message about there not being a loader for `.rttm` files:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3540f768261e> in <module>()
      2 from pyannote.database import get_protocol
      3 protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset')
----> 4 for resource in protocol.train():
      5     print(resource["uri"])

2 frames
/usr/local/lib/python3.6/dist-packages/pyannote/database/custom.py in gather_loaders(entries, database_yml)
    205             if path.suffix not in LOADERS:
    206                 msg = f"No loader for file with '{path.suffix}' suffix"
--> 207                 raise TypeError(msg)
    208 
    209             # load custom loader class

TypeError: No loader for file with '.rttm' suffix
```

Here's a public Google Colab file where you can see the issue. It only takes a minute or so to run.
https://colab.research.google.com/drive/1ErF8KOk-s11zUXjOEbZnRguvzj2SBafC

Really appreciate any advice on how to fix this. Thanks!

**Comment by hbredin** [comment]
For some reason, [loader entrypoints](https://github.com/pyannote/pyannote-database/blob/47f7109a37d5e72c264707c54e91806a6ecc4d86/setup.py#L45-L49) are not detected.

Restarting the Google Colab runtime after the installation of `pyannote.database` seems to fix the issue.

**Comment by hbredin** [comment]
Oh, and, thanks a lot for setting up this Google Colab -- I really appreciate it.
Much better than the usual "It does not work -- can you fix this, please?" message 👍

**Comment by micahjon** [comment]
Thanks @hbredin!

I followed your instructions and restarted the Colab runtime. Unfortunately, the next time I run this code, I get a different error, regarding there not being a protocol for the `AMI` database:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pyannote/database/__init__.py in get_database(database_name, **kwargs)
    118     try:
--> 119         database = DATABASES[database_name]
    120 

KeyError: 'AMI'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
2 frames
<ipython-input-1-3540f768261e> in <module>()
      1 # Run some sample code to make sure I understand how this works
      2 from pyannote.database import get_protocol
----> 3 protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset')
      4 for resource in protocol.train():
      5     print(resource["uri"])

/usr/local/lib/python3.6/dist-packages/pyannote/database/__init__.py in get_protocol(name, preprocessors)
    157 
    158     database_name, task_name, protocol_name = name.split(".")
--> 159     database = get_database(database_name)
    160     protocol = database.get_protocol(
    161         task_name, protocol_name, preprocessors=preprocessors

/usr/local/lib/python3.6/dist-packages/pyannote/database/__init__.py in get_database(database_name, **kwargs)
    134             )
    135             msg = msg.format(name=database_name)
--> 136         raise ValueError(msg)
    137 
    138     return database(**kwargs)

ValueError: Could not find any protocol for "AMI" database. Please refer to pyannote.database documentation to learn how to define them: https://github.com/pyannote/pyannote-database
```

It's like it's not finding the AMI protocol, even thought the `database.yml` file includes it:

```yaml
Protocols:
  AMI:
    SpeakerDiarization:
      MixHeadset:
        train:
```

Any idea what's going on? It should be easy to replicate using the colab link above. Thanks again!

**Comment by hbredin** [comment]
Looks like you forgot to reset the PYANNOTE_DATABASE_CONFIG environment variable after restarting the runtime and **before** importing `pyannote.database`.

**Comment by micahjon** [comment]
Hey, thanks again! Didn't realizing restarting was a part of the colab workflow.
