### ISSUE TITLE
pyannote.database plugin for "CallHome"

### ISSUE THREAD

**Issue by sushant-hiray** [pyannote/pyannote-database#7]
Hey Team,

Thanks for providing this common interface. We've been using it at @SEERNET  for creating plugins for our internal datasets. We also created a db-plugin for the [CABank-CallHome](https://talkbank.org/access/CABank/CallHome/eng.html) dataset [here](https://github.com/SEERNET/pyannote-db-callhome). 

Would definitely love to push it upstream in the `pyannote-org` for the community.

Cheers!

/cc @venkatesh-1729

**Comment by hbredin** [comment]
That's great, thanks. 

I don't really have time to test it right now but I'll get back to you once I did.

**Comment by hbredin** [comment]
Closing this old issue as this will most likely not happen: custom protocols in `database.yml` are now the recommended way of adding databases.
