### ISSUE TITLE
problem with pyannote

### ISSUE THREAD

**Issue by Gabrielk99** [pyannote/pyannote-database#70]
Hi, i have a problem when i execute the tutorial, well, this msg is returned from after execute program:

FileNotFoundError: Could not find file "EN2002a.Mix-Headset" in the following location(s):
 - /home/gabriel/Desktop/My_tasks/IA-DEEPLEARNING/IC/Codigos/amicorpus/*/audio/EN2002a.Mix-Headset.wav

i dont know why this error happen, can u help me?

**Comment by hbredin** [comment]
Did you download the AMI corpus? 
Can you search for file `EN2002a.Mix-Headset.wav` and report where it actually is?

**Comment by Gabrielk99** [comment]
sorry, im with covid-19 and i had pause my work, but, i can answer you now, and i used the script to download the database that is organized in my directory as

MAIN> nivel1
AMI>nivel2
amicorpus>nivel3
data...nivel4
code...nivel2

where the data is the files, and contain the EN2002a.Mix-Headset.wav

**Comment by Gabrielk99** [comment]
omg, i see whats is the problem now, sorry man, and thank you.
