### ISSUE TITLE
Multiple preprocessor for same field 

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-database#80]
Hey,

For that (now cursed) VTC pipeline, if we want to keep things neat, I'll be needing the support for _lists of preprocessors_ for a given field. Let me explain myself: let's say I have 2 preprocessors for `file["annotation"]`, `LabelMapper` and `VoiceTypeClassifierPreprocessor`. I need to be able to chain them, the solution being pretty easy:

```python
protocol = get_protocol("Db.ProtocolType.MyProtocol", preprocessors={
    "audio": FileFinder(),
    "annotation": [LabelMapper(), VoiceTypeClassifierPreprocessor(classes=..., unions=...)]
})
```

Obviously, the order of preprocessors in the list is important.

Would you be ok with me adding support for this in pyannote-db, while keeping the support for the current "single preprocessor" API?

**Comment by hbredin** [comment]
Did you have a look at `ProtocolFile` lazy keys? You have no idea what you are getting into! :-)

Why not simply use [function composition](https://www.geeksforgeeks.org/function-composition-in-python/) and pass the resulting preprocessor?

**Comment by hadware** [comment]
I did have a look, and I can confidently say that I understand about a quarter of it :clown_face: 

I was just planning on doing kind of what you suggested, using a simple "shim" to iterate through the chained processors. The idea would be to replace the `List[Processor]` by something like this:

```python
from typing import List

from pyannote.database.protocol.protocol import Preprocessor
from pyannote.database.protocol.protocol import ProtocolFile


class ProcessorChain(Preprocessor):

    def __init__(self, preprocessors: List[Preprocessor], key: str):
        self.procs = preprocessors
        self.key = key

    def __call__(self, file: ProtocolFile):
        file_cp = ProtocolFile(precomputed=file)
        for proc in self.procs:
            out = proc(file_cp)
            file_cp[self.key] = out

        return out
```

**Comment by hadware** [comment]
(In case it wasn't clear, this snippet was suggested as a modification, for a potential PR)

**Comment by hbredin** [comment]
It was crystal 💎 clear!

You'd like to add an `elif isinstance(preprocessor, list)` condition somewhere around [here](https://github.com/pyannote/pyannote-database/blob/54e3e7d5c1a8a51218a964ad76c7e7f97244af63/pyannote/database/protocol/protocol.py#L324), right? 

I am still worried that this might have unintended side effects when the original `file` contains lazy keys (i.e. keys that are only computed when they are accessed). 

In particular, `file_cp = ProtocolFile(precomputed=file)` has [the side effect](https://github.com/pyannote/pyannote-database/blob/54e3e7d5c1a8a51218a964ad76c7e7f97244af63/pyannote/database/protocol/protocol.py#L81) of calling `abs(file)`, which itself calls [`dict(self._store)`](https://github.com/pyannote/pyannote-database/blob/54e3e7d5c1a8a51218a964ad76c7e7f97244af63/pyannote/database/protocol/protocol.py#L111), which (I think, to be verified), calls every preprocessors, even lazy ones which are not needed by your chain of preprocessors.
