### ISSUE TITLE
Training on Jamendo Corpus

### ISSUE THREAD

**Issue by FrancescoBonzi** [pyannote/pyannote-database#81]
Hi!

I would like to train one of your pyannote.audio models using the Jamendo Corpus dataset available here: https://zenodo.org/record/2585988#.Yh9QgBPMJhE

Unfortunately I have some problems defining the custom data loader. Each audio track has a single label file, in .lab format with _start end label_ format and this is different from the CTMLoader.

I wrote the following files.

database.yml:
`Databases:
  Jamendo:
    - /path_to_jamendo/{uri}.mp3
    - /path_to_jamendo/{uri}.ogg
Protocols:
  Jamendo:
    Protocol:
      JamendoProtocol:
        train:
            uri: /path_to_jamendo/filelists/train
            annotation: /path_to_jamendo/labels/{uri}.lab
        development:
            uri: /path_to_jamendo/filelists/valid
            annotation: /path_to_jamendo/labels/{uri}.lab
        test:
            uri: /path_to_jamendo/filelists/test
            annotation: /path_to_jamendo/labels/{uri}.lab`

setup.py:
`from setuptools import setup, find_packages
setup(
    name="jamendo_lab_loader",
    packages=find_packages(),
    install_requires=[
        "pyannote.database >= 4.0",
    ],
    entry_points={
        "pyannote.database.loader": [
            ".lab = jamendo_lab_loader.loader:LabLoader",
        ],
    }
)`

I don't know how to write the loader.py and how to use it. Do you have any suggestions?
Thank you for sharing this great pyannote work. Hope you can help me.
Francesco

**Comment by hbredin** [comment]
Before writing your own data loader, I'd suggest you convert your `.lab` files into `.rttm` files. 

If you really want to write your own data loader, I'd suggest you have a look at the [`RTTMLoader`](https://github.com/pyannote/pyannote-database/blob/54e3e7d5c1a8a51218a964ad76c7e7f97244af63/pyannote/database/loader.py#L100) example.

**Comment by FrancescoBonzi** [comment]
Thank you Hervé for your answer. Looking at RTTMLoader and UEMLoader I succeeded in writing a custom data loader.

**Comment by hbredin** [comment]
Since I stumbled on .lab files in the past, would you like to contribute a PR adding support for .lab directly in pyannote.database?

**Comment by FrancescoBonzi** [comment]
Of course! I did it, check it out and let me know if there are some problems with it
