### ISSUE TITLE
Deprecated plugin system

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-database#83]
Hey,

http://github.com/pyannote/pyannote-db-template is now DEPRECATED. I'm still using this system for custom DB that don't really fit the RTTM/UEM/LST model, or have custom ways of organizing files. What should be used instead of deprecated repo?

**Comment by hbredin** [comment]
Can you provide an example of such custom DB that doesn't fit?

**Comment by hadware** [comment]
errhh it's a _very_ private DB (medical data) that we have, it's based on TextGrid annotations. To prevent the "derived dataset duplication hell", I'm extremely reliant on annotation-derivation that are directly in my `Protocol` classes, so the db-plugin system works really well for me in that case.

I'm not saying it's not working anymore, i'm just wondering if support for this will be dropped at some point, or if it's not the "right way" of doing things any more.

**Comment by hbredin** [comment]
FYI -- this PR (which will be part of upcoming 5.x branch) removes support for plugins.

**Comment by hadware** [comment]
How would you go about making a `Protocol` that doesn't rely on preprared UEM/RTTM/LST  files in `5.x` then?

**Comment by hbredin** [comment]
[Custom data loaders](https://github.com/pyannote/pyannote-database#custom-data-loaders) will still be supported. 

Therefore, a combination of (TextGrid ?) data loader and preprocessors could maybe do the trick. I guess getting access to one of your (very private) plugins would help me answer your question :)
