### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by askrobola** [pyannote/pyannote-database#84]
Upon trying to run the following code to label preprocessors:

from pyannote.database import FileFinder
preprocessors = {'audio': FileFinder()}

I ran into the attribute error below: 

AttributeError                            Traceback (most recent call last)
Input In [12], in <cell line: 2>()
      1 from pyannote.database import FileFinder
----> 2 preprocessors = {'audio': FileFinder()}

File ~\Anaconda3\lib\site-packages\pyannote\database\util.py:94, in FileFinder.__init__(self, database_yml)
     89 with open(self.database_yml, "r") as fp:
     90     config = yaml.load(fp, Loader=yaml.SafeLoader)
     92 self.config_: Dict[DatabaseName, Union[PathTemplate, List[PathTemplate]]] = {
     93     str(database): path
---> 94     for database, path in config.get("Databases", dict()).items()
     95 }

AttributeError: 'NoneType' object has no attribute 'items'

Could anyone please advise on how to overcome this issue? database config and database.yml contents below.

echo $PYANNOTE_DATABASE_CONFIG:
/Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/database.yml

database.yml:
Databases:
AMI: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/*/audio/{uri}.wav
MUSAN: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/MUSAN/musan/music/{uri}.wav 

Protocols:
   AMI:
      SpeakerDiarization:
        MixHeadset:
           train:
              uri: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.train.lst
              annotation: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.train.rttm
              annotated: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.train.uem
           development:
              uri: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.development.lst
              annotation: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.development.rttm
              annotated: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.development.uem
           test:
              uri: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.test.lst
              annotation: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.test.rttm
              annotated: /Users/askrobola/Documents/GitHub/pyannote-audio/tutorials/Sandbox/AMI/MixHeadset.test.uem

**Comment by hbredin** [comment]
Would you mind sharing a link to a Google Colab containing a minimum reproducible example that I can quickly (understand: in less than 5 minutes) run to reproduce the error?

**Comment by askrobola** [comment]
Sure, google colab sharing function is down for some reason so I can post the link. I apologize if the colab is not up to speed, I currently work out of juypter notebook due to corporate settings.

https://colab.research.google.com/drive/1jnvH1z38lYCSMGUmjZ7eujICaNHKJJ9g

**Comment by hbredin** [comment]
Looks like the link is not public and requires permissions.

**Comment by askrobola** [comment]
https://colab.research.google.com/drive/1jnvH1z38lYCSMGUmjZ7eujICaNHKJJ9g?usp=sharing

apologies, google drive does not operate on my workstation so I switched to a personal device. The ling should work now.

**Comment by hbredin** [comment]
I do have access but this Colab is not unfortunately self-contained and I cannot run it online.
