### ISSUE TITLE
LABLoader import error

### ISSUE THREAD

**Issue by waoooNiuBility** [pyannote/pyannote-database#88]
Packages installed using pip install pyannote.database command, do not have the latest updates, such as LABLoader

cannot import name 'LABLoader' from 'pyannote.database.loader'

**Comment by hbredin** [comment]
Support for `LAB` files has only been added in the `develop` branch. It will be part of next release.

In the meantime, you can install `pyannote.database` from the `develop` branch.

```bash
pip install https://github.com/pyannote/pyannote-database/archive/develop.zip
```
