### ISSUE TITLE
FileFinder doesn't work without development subset

### ISSUE THREAD

**Issue by yinruiqing** [pyannote/pyannote-database#9]
```python
       for method in methods:
            try:
                protocol.progress = False
                file_generator = getattr(protocol, method)()
                first_item = next(file_generator)
            except AttributeError as e:
                continue
            except NotImplementedError as e:
              continue
```
The first element in methods list is 'development'. If  'development' doesn't in protocol, FileFinder doesn't work.

**Comment by hbredin** [comment]
Can you please provide me with a reproducible example showing what is wrong exactly?
What is the expected behavior?
What is the actual behavior?

**Comment by yinruiqing** [comment]
An example is [here](https://gist.github.com/yinruiqing/01911120596deda0f8691e7ce7c81e68).

**Comment by hbredin** [comment]
I cannot test this as I get the following error:

```python
>>> list(protocol_eastender.test())[:4]
```
```
FileNotFoundError: [Errno 2] No such file or directory: 'eastenders.all.lst'
```

**Comment by hbredin** [comment]
Thanks. Version 1.3.1 has just been released that fixes this issue.
